import { useState, useEffect } from 'react';
import { MovieConductor } from './core/conductor/MovieConductor';
import { WatchlistState } from './types/domain';

interface AppProps {
  conductor: MovieConductor;
}

function App({ conductor }: AppProps) {
  // Initialize with current state from conductor
  const [state, setState] = useState<WatchlistState>(conductor.getState());

  useEffect(() => {
    // Subscribe to conductor updates
    const unsubscribe = conductor.subscribe((newState) => {
      setState(newState);
    });

    // Cleanup subscription on unmount
    return () => unsubscribe();
  }, [conductor]);

  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    if (value.length === 0) {
      conductor.dispatch({ type: 'LOAD_MOVIES' });
    } else if (value.length > 2) {
      conductor.dispatch({ type: 'SEARCH', payload: value });
    }
  };

  const handleAddRandomMovie = () => {
    const dummyMovie = {
      id: '', // Placeholder, will be ignored/generated by DB
      title: `New Movie ${new Date().toLocaleTimeString()}`,
      posterPath: null,
      runtime: 120,
      releaseDate: new Date().toISOString().split('T')[0],
      overview: 'This is a test movie added from the new Conductor architecture.',
      voteAverage: 5.0
    };
    conductor.dispatch({ type: 'ADD_MOVIE', payload: dummyMovie });
  };

  return (
    <div style={{ padding: '20px', fontFamily: 'sans-serif', color: '#fff', backgroundColor: '#0B0E14', minHeight: '100vh' }}>
      <h1>InFocus CineLog V2</h1>
      
      <div style={{ marginBottom: '20px' }}>
        <input 
          type="text" 
          placeholder="Suche..." 
          onChange={handleSearchChange}
          style={{
            padding: '10px',
            fontSize: '16px',
            width: '100%',
            maxWidth: '300px',
            marginBottom: '10px',
            borderRadius: '4px',
            border: '1px solid #333',
            backgroundColor: '#1f2937',
            color: 'white',
            display: 'block'
          }}
        />
        
        <div style={{ marginTop: '10px' }}>
            <button 
            onClick={() => conductor.dispatch({ type: 'LOAD_MOVIES' })}
            style={{
                padding: '10px 20px',
                fontSize: '16px',
                cursor: 'pointer',
                backgroundColor: '#3b82f6',
                color: 'white',
                border: 'none',
                borderRadius: '4px',
                marginRight: '10px'
            }}
            >
            Reload
            </button>

            <button 
            onClick={handleAddRandomMovie}
            disabled={state.status === 'loading'}
            style={{
                padding: '10px 20px',
                fontSize: '16px',
                cursor: state.status === 'loading' ? 'not-allowed' : 'pointer',
                backgroundColor: '#10b981',
                color: 'white',
                border: 'none',
                borderRadius: '4px'
            }}
            >
            ➕ Add Random Movie
            </button>
        </div>
      </div>

      {state.status === 'loading' && (
        <div style={{ color: '#fbbf24', marginBottom: '10px' }}>⏳ Updating...</div>
      )}

      {state.error && (
        <div style={{ color: '#ef4444', marginBottom: '20px', padding: '10px', border: '1px solid #ef4444', borderRadius: '4px' }}>
          Error: {state.error}
        </div>
      )}

      {state.items.length > 0 && (
        <ul style={{ listStyle: 'none', padding: 0 }}>
          {state.items.map((movie) => (
            <li 
              key={movie.id} 
              style={{ 
                marginBottom: '10px', 
                padding: '10px', 
                border: '1px solid #333', 
                borderRadius: '4px', 
                display: 'flex', 
                justifyContent: 'space-between', 
                alignItems: 'center',
                backgroundColor: '#111827'
              }}
            >
              <div>
                <strong>{movie.title}</strong>
                <span style={{ marginLeft: '10px', color: '#9ca3af', fontSize: '0.9em' }}>
                  ({movie.releaseDate?.split('-')[0] || 'N/A'})
                </span>
              </div>
              
              <button
                onClick={() => conductor.dispatch({ type: 'REMOVE_MOVIE', payload: movie.id })}
                style={{
                  padding: '5px 10px',
                  backgroundColor: '#ef4444',
                  color: 'white',
                  border: 'none',
                  borderRadius: '4px',
                  cursor: 'pointer',
                  marginLeft: '10px'
                }}
                title="Delete Movie"
              >
                🗑️
              </button>
            </li>
          ))}
        </ul>
      )}
      
      {state.status === 'idle' && state.items.length === 0 && !state.error && (
        <p style={{ color: '#666' }}>No movies found. Try searching or adding one.</p>
      )}
    </div>
  );
}

export default App;