import { useState, useEffect } from 'react';
import { MovieConductor } from './core/conductor/MovieConductor';
import { WatchlistState } from './types/domain';

interface AppProps {
  conductor: MovieConductor;
}

function App({ conductor }: AppProps) {
  // Initialize with current state from conductor
  const [state, setState] = useState<WatchlistState>(conductor.getState());

  useEffect(() => {
    // Subscribe to conductor updates
    const unsubscribe = conductor.subscribe((newState) => {
      setState(newState);
    });

    // Cleanup subscription on unmount
    return () => unsubscribe();
  }, [conductor]);

  const handleLoadMovies = () => {
    conductor.dispatch({ type: 'LOAD_MOVIES' });
  };

  const handleSearchChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const value = e.target.value;
    if (value.length === 0) {
      conductor.dispatch({ type: 'LOAD_MOVIES' });
    } else if (value.length > 2) {
      conductor.dispatch({ type: 'SEARCH', payload: value });
    }
  };

  return (
    <div style={{ padding: '20px', fontFamily: 'sans-serif', color: '#fff', backgroundColor: '#0B0E14', minHeight: '100vh' }}>
      <h1>InFocus CineLog V2</h1>
      
      <div style={{ marginBottom: '20px' }}>
        <input 
          type="text" 
          placeholder="Suche..." 
          onChange={handleSearchChange}
          style={{
            padding: '10px',
            fontSize: '16px',
            width: '100%',
            maxWidth: '300px',
            marginBottom: '10px',
            borderRadius: '4px',
            border: '1px solid #333',
            backgroundColor: '#1f2937',
            color: 'white'
          }}
        />
        <br />
        <button 
          onClick={handleLoadMovies}
          disabled={state.status === 'loading'}
          style={{
            padding: '10px 20px',
            fontSize: '16px',
            cursor: state.status === 'loading' ? 'not-allowed' : 'pointer',
            backgroundColor: '#3b82f6',
            color: 'white',
            border: 'none',
            borderRadius: '4px'
          }
        >
          {state.status === 'loading' ? '⏳ Lade Daten...' : 'Load Movies'}
        </button>
        <button 
          onClick={() => {
            const dummyMovie = {
              id: '', // Placeholder, will be ignored/generated by DB
              title: `New Movie ${new Date().toLocaleTimeString()}`,
              posterPath: null,
              runtime: 120,
              releaseDate: new Date().toISOString().split('T')[0],
              overview: 'This is a test movie added from the new Conductor architecture.',
              voteAverage: 5.0
            };
            conductor.dispatch({ type: 'ADD_MOVIE', payload: dummyMovie });
          }}
          disabled={state.status === 'loading'}
          style={{
            padding: '10px 20px',
            fontSize: '16px',
            cursor: state.status === 'loading' ? 'not-allowed' : 'pointer',
            backgroundColor: '#10b981',
            color: 'white',
            border: 'none',
            borderRadius: '4px',
            marginLeft: '10px'
          }}
        >
          ➕ Add Random Movie
        </button>
      </div>

      {state.error && (
        <div style={{ color: 'red', marginBottom: '20px' }}>
          Error: {state.error}
        </div>
      )}

      {state.items.length > 0 && (
        <ul style={{ listStyle: 'none', padding: 0 }}>
          {state.items.map((movie) => (
            <li key={movie.id} style={{ marginBottom: '10px', padding: '10px', border: '1px solid #333', borderRadius: '4px' }}>
              <strong>{movie.title}</strong>
              <span style={{ marginLeft: '10px', color: '#888' }}>
                ({movie.releaseDate?.split('-')[0]})
              </span>
            </li>
          ))}
        </ul>
      )}
      
      {state.status === 'idle' && state.items.length === 0 && !state.error && (
        <p style={{ color: '#666' }}>No movies loaded yet. Click the button above.</p>
      )}
    </div>
  );
}

export default App;
